export enum HttpStatus {
    OK = "OK",
    CREATED = "CREATED",
    BAD_REQUEST = "BAD REQUEST",
    FORBIDDEN = "FORBIDDEN",
    NOT_FOUND = "NOT FOUND",
    INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR"
}